---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: exo
  name: exo
  namespace: demo-exo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exo
