apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-exo
spec:
  project: default
  source:
    repoURL: 'https://github.com/abdullahsikder/gitops-demo.git'
    path: example-app/overlay/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}